backend:
  name: git-gateway
  identity_url: "https://kbf2018.netlify.com/.netlify/identity"
  gateway_url: "https://kbf2018.netlify.com/.netlify/git"
  branch: master

publish_mode: editorial_workflow

media_folder: media_folder

collections: # A list of collections the CMS should be able to edit
  - name: blog # Used in routes, ie.: /admin/collections/:slug/edit
    label: Blog Post # Used in the UI, ie.: New Post
    folder: content/blog # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/_index"
    fields: # The fields each document in this collection have
      - { label: Date/Time, name: date, widget: datetime }
      - { label: Post Title, name: title, widget: string }
      - { label: Content, name: body, widget: markdown }
      - {
          label: Gallery,
          name: gallery,
          widget: list,
          required: false,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Caption, name: caption, widget: text },
            ],
        }

  - name: settings # Used in routes, ie.: /admin/collections/:slug/edit
    label: Settings
    editor:
      preview: false
    files:
      - file: config.toml
        label: Site Settings
        name: site
        fields:
          - { label: Site Title, name: title, widget: string }
# backend:
#   name: git-gateway
#   identity_url: "https://festive-booth-4008fd.netlify.com/.netlify/identity"
#   gateway_url: "https://festive-booth-4008fd.netlify.com/.netlify/git"
#   branch: master

# media_folder: static/img
# public_folder: /img

# collections:
#   - name: "blog"
#     label: "Blog"
#     folder: "content/blog"
#     create: true
#     slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
#     editor:
#       preview: true
#     fields:
#       - { label: "Title", name: "title", widget: "string" }
#       - { label: "Publish Date", name: "date", widget: "datetime" }
#       - { label: "Description", name: "description", widget: "string" }
#       - { label: "Body", name: "body", widget: "markdown" }
